# ./docker-compose.yml
version: '3'

services:
  app:
    image: adhocore/lemp:8.3
    # For different app you can use different names. (eg: )
    container_name: domestic-airlines-website
    volumes:
      # app source code
      - ./www:/var/www/html:Z
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:Z
      # db data persistence
      - db_data:/var/lib/mysql
      # Here you can also volume php ini settings
      # - /path/to/zz-overrides:/usr/local/etc/php/conf.d/zz-overrides.ini
    ports:
      # Binds the website to http://localhost:2680
      - 2680:80
    environment:
      MYSQL_DATABASE: domesticdb
      MYSQL_USER: domestic_airlines_website
      MYSQL_PASSWORD: jS8@j%n6nsj#q3
      # for postgres you can pass in similar env as for mysql but with PGSQL_ prefix
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_data: {}
