# ./docker-compose.yml
version: '3'

services:
  app:
    image: adhocore/lemp:8.3
    # For different app you can use different names. (eg: )
    container_name: domestic-airlines-website
    volumes:
      # app source code
      - ./www:/var/www/html:Z
      # db data persistence
      - db_data:/var/lib/mysql
      # Here you can also volume php ini settings
      # - /path/to/zz-overrides:/usr/local/etc/php/conf.d/zz-overrides.ini
    ports:
      # Binds the website to http://localhost:2680
      - 2680:80
    environment:
      MYSQL_ROOT_PASSWORD: j$diw9@i3js9sks
      MYSQL_DATABASE: domesticdb
      MYSQL_USER: domestic_airlines_website
      MYSQL_PASSWORD: jS8@j%n6nsj#q3
      # for postgres you can pass in similar env as for mysql but with PGSQL_ prefix

volumes:
  db_data: {}
